pim_enrich_job_instance_rest_import_get:
    path: /rest/import/{identifier}
    defaults: { _controller: pim_enrich.controller.rest.job_instance:getImportAction, _format: json }
    methods: [GET]

pim_enrich_job_instance_rest_import_put:
    path: /rest/import/{identifier}
    defaults: { _controller: pim_enrich.controller.rest.job_instance:putImportAction, _format: json }
    methods: [PUT, POST]

pim_enrich_job_instance_rest_import_delete:
    path: /rest/import/{code}
    defaults: { _controller: pim_enrich.controller.rest.job_instance:deleteImportAction, _format: json }
    methods: [DELETE]

pim_enrich_job_instance_rest_import_launch:
    path: /rest/import/{code}/launch
    defaults: { _controller: pim_enrich.controller.rest.job_instance:launchImportAction, _format: json }
    methods: [POST, GET]

pim_enrich_job_instance_rest_export_get:
    path: /rest/export/{identifier}
    defaults: { _controller: pim_enrich.controller.rest.job_instance:getExportAction, _format: json }
    methods: [GET]

pim_enrich_job_instance_rest_export_put:
    path: /rest/export/{identifier}
    defaults: { _controller: pim_enrich.controller.rest.job_instance:putExportAction, _format: json }
    methods: [PUT, POST]

pim_enrich_job_instance_rest_export_delete:
    path: /rest/export/{code}
    defaults: { _controller: pim_enrich.controller.rest.job_instance:deleteExportAction, _format: json }
    methods: [DELETE]

pim_enrich_job_instance_rest_export_launch:
    path: /rest/export/{code}/launch
    defaults: { _controller: pim_enrich.controller.rest.job_instance:launchExportAction, _format: json }
    methods: [POST, GET]
