pim_user_user_group_rest_index:
    path: /{_format}
    defaults: { _controller: pim_user.controller.user_group_rest:indexAction, _format: json }
    requirements:
        _format: json
        method: GET
